var data= [
    {id:'1',
    category: "phone",
    nameSP: " Điện Thoại iphone 5 16GB Chính hãng",
    price: 3000000,
    rate:5,
    title:"Điện Thoại tại Béo Store đã được kiểm duyệt rất kĩ trước khi giao tới cho khách hàng. Máy Cấu Hình Cao nhưng giá lại cực rẻ. đem tới trải nghiệm tốt nhất cho khách",
    image:"image/SP/iphone5.jpg"
    },
    {id:'5',
    category:"houseware",
    nameSP: " Bàn là hơi nước Konka KZ-GT17 cây đứng",
    price: 1000000,
    rate:5,
    title:"Bàn là hơi nước Konka KZGT17 cây đứng hàng nhập khẩu chính hãng,Trong cuộc sống hiện đại bàn là hơi nước là vật dụng không thể thiếu trong gia đình,Bàn là hơi nước cũng phù hợp với các shop bán quần áo",
    image:"image/SP/banla.jpg"
    },
    {id:'6',
    category:"houseware",
    nameSP: " Tivi LED Philips 43 Inch Full HD - 43PFT5583/74 ",
    price: 3500000,
    rate:5,
    title:"TV màn hình LED Full HD,Được tạo ra để đem lại niềm vui cho người xem, TV Philips dòng 5500 mang đến hình ảnh chất lượng cao trong thiết kế màn hình thon mảnh. Bên cạnh phong cách tối giản phù hợp với mọi thiết kế nội thất thì TV này còn có kích thước nhỏ gọn mà người dùng có thể đặt nó ở bất cứ chỗ nào trong nhà",
    image:"image/SP/tivi.png"
    },
    {id:'7',
    category:"houseware",
    nameSP: " Quạt sạc SUNHOUSE  chính hãng",
    price: 450000,
    rate:5,
    title:"Khả năng điều chỉnh độ cao: KhôngKhả năng quay đảo chiều: CóBảng điều khiển: Nút ấnĐèn báo: Đèn báo đang sạc và sạc đầyĐèn chiếu sáng: CóThương hiệu: SUNHOUSEXuất xứ: Trung QuốcBảo hành: 12 tháng",
    image:"image/SP/mayquat.jpg"
    },
    {id:'3',
    category: "phone",
    nameSP: " Apple iphone 7 32G chính hảng Apple",
    price: 5000000,
    rate:5,
    title:"iPhone 7 32GB vẫn mang trên mình thiết kế quen thuộc của từ thời iPhone 6 nhưng có nhiều thay đổi lớn về phần cứng, dàn loa stereo và cấu hình cực mạnh.Camera trước tăng lên 7 MPMột sự cải thiện đáng kể so với iPhone 6s trước đó, những tấm ảnh chụp selfie của bạn càng thêm độ chi tiết và sắc nét.",
    image:"image/SP/iphone7.jpg"
    },
    {id:'8',
    category:"houseware",
    nameSP: " Bình nước nóng gián tiếp Ariston BLU 30 R 2.5 FE",
    price: 1500000,
    rate:5,
    title:"Là chuyên gia hàng đầu trên thế giới trong lĩnh vực gia nhiệt, Ariston hiểu rằng tầm quan trọng của thanh đốt được ví như trái tim của con người. Bình nước nóng Ariston BLU sử dụng thanh đốt 100% đồng, mang lại hiệu quả làm nóng nhanh và bền bỉ với thời gian. Bạn hoàn toàn có thể yên tâm với độ bền vượt trội của bình nước nóng Ariston.",
    image:"image/SP/binhNuocNong.jpg"
    },
    {id:'4',
    category:"phone",
    nameSP: " iPhone x 64GB cũ nguyên zin hàng 99%",
    price: 7000000,
    rate:5,
    title:"Tháng 9/2017, Apple giới thiệu iPhone X, chiếc điện thoại kỷ niệm 10 năm iPhone ra đời với hàng loạt cải tiến mang tính đột phá, và mới đây là iPhone 12, 12 Mini, 12 Pro và iPhone 12 Pro Max gợi lên nhiều hứng thú cho giới công nghệ cũng như cộng đồng người dùng giống như những gì họ đã làm 10 năm trước khi ra mắt mẫu iPhone đầu tiên. Tuy nhiên, cũng vì được nâng cấp toàn diện mà iPhone X có giá bán rất cao. Lúc này, mua iPhone X cũ là sự lựa chọn rất đáng để người dùng phải cân nhắc.",
    image:"image/SP/iphonex.jpg"
    },
    {id:'9',
    category:"houseware",
    nameSP: " Nồi cơm điện Electrolux 1.8L E2RC1-320W",
    price: 600000,
    rate:5,
    title:"Nồi cơm điện nắp rời Electrolux E2RC1-320W được thiết kế với kiểu dáng nắp rời, sẽ giúp bạn dễ dàng với các thao tác khi sử dụng cũng như khi chùi rửa, vệ sinh cho nồi. Nồi cơm điện nắp rời này trang bị nút gạt chế độ nấu, cùng đèn LED báo sẽ giúp dễ dàng kiểm soát được chế độ hoạt động của nồi, tay cầm cách nhiệt, đảm bảo sự an toàn và dễ dàng cho bạn khi cầm nắm, di chuyển, lòng nồi được làm bằng hợp kim nhôm, phủ lớp chống dính, giúp cơm không bị bám dính ở đáy nồi, tạo sự thuận tiện cho bạn khi sử dụng và chùi rửa.",
    image:"image/SP/noicom.jpg"
    },
    {id:'2',
    category: "phone",
    nameSP: " Apple iPhone 6S Plus 64GB cũ chính hãng",
    price: 4000000,
    rate:5,
    title:"Hiện APPLE IPHONE 6S PLUS 64GB HỒNG CŨ - ĐẸP giá thời điểm hiện tại 4.820.000 còn hàng tại HCM. Chi tiết hơn em xin được liên hệ qua SĐT để hỗ trợ tốt nhất cho mình ạ.. Mình vui lòng để ý điện thoại giúp em.Thân mến.",
    image:"image/SP/iphone6.jpg"
    },
    {id:'10',
    category: "quanAo",
    nameSP: " Áo polo nam ai cập,vải CVC,thun cao cấp",
    price: 300000,
    rate:5,
    title:"CVC có cảm giác thoáng mát, bề mặt vải bóng mịn, không nhăn nhàu, không cần là ủi. Đặc biệt, với khả năng bền màu, bề mặt vải luôn mới sau nhiều lần giặt, bề mặt tiếp xúc với da mềm mại.- Đây là loại vải có tính chất pha trộn giữa tính chất cotton (thấm hút mồ hôi, hút ẩm, mềm mại cho da, dễ nhuộm) và tính chất PE (sáng bóng, không nhăn, thoát ẩm tốt). Tuy nhiên, tính chất vải cotton trội hơn.",
    image:"image/SP/aopolo.jpg"
    },
    {id:'11',
    category: "quanAo",
    nameSP: " Quần Kaki Nam Chất nhẹ Dáng Âu Vicero",
    price: 300000,
    rate:5,
    title:"Chất lượng sản phẩm rất tốt, so với việc mua tại cửa hàng, sẽ bị phải tính thêm giá chi phí nhân viên, chi phí mặt bằng, chi phí điện nước,...Nên giá mua tại cửa hàng sẽ đương nhiên sẽ cao hơn, Khách hàng mua onl sẽ không bị shop tính thêm chi phí đó vào giá sản phẩm.",
    image:"image/SP/quankaki.jpg"
    },
    {id:'12',
    category: "quanAo",
    nameSP: " Váy Hoa Nhí, Đầm Xinh Họa Tiết Hoa Nhí",
    price: 300000,
    rate:5,
    title:"Kín đáo nhưng ngọt ngào khó cưỡng, nàng diện Princess Dress chiếm trọn tình cảm!Màu sắc và hoạ tiết đủ làm cho bất kì ai nhìn nàng đều siêu lòng. Chỉ cần một cái chạm nhẹ cũng đủ để các nàng rinh em ấy về tủ đồ của mình. Em đẹp quyến rũ đúng với cái tên của mình Princess.",
    image:"image/SP/vaybong.jpg"
    },
    {id:'13',
    category: "quanAo",
    nameSP: " Áo thun bé trai trẻ em cotton 4 chiều",
    price: 300000,
    rate:5,
    title:" Áo thun cho bé form dáng rộng rãi, đường kim mũi chỉ cẩn thận. Thích hợp diện trong các dịp đi học, du lịch, dạo phố, đi biển, tham quan dã ngoại, cắm trại, shopping, …",
    image:"image/SP/aothuntreem.jpg"
    },
    {id:'14',
    category: "quanAo",
    nameSP: " Bộ đồ ngủ nữ  thời trang Everest",
    price: 300000,
    rate:5,
    title:" Bộ ngủ lụa bên shop đều được tuyển chọn kĩ càng về chất liệu, mẫu mã, đường may chuẩn từng centimet nha .Đặc biệt chất liệu vải thoáng mát và tạo nên sự thoải mái cho người dùng. Màu sắc bắt mắt cũng là một tiêu chuẩn tạo nên một bộ đồ ngủ pijama chất lượng.Hoạ tiết trơn công nghệ cao tuyệt đối không nhem, không phai màu ",
    image:"image/SP/dongulua.jpg"
    },

]
 var local =localStorage.setItem('data',JSON.stringify(data))
 