var data= [
    {id:'1',
    category: "phone",
    nameSP: " Apple iphone 5",
    price: 3000000,
    rate:5,
    title:"apple giá rẻ chính hãng",
    image:"image/SP/iphone5.jpg"

    },
    {id:'2',
    category: "phone",
    nameSP: " Apple iphone 6",
    price: 4000000,
    rate:5,
    title:"apple giá rẻ chính hãng",
    image:"image/SP/iphone6.jpg"
    },
    {id:'3',
    category: "phone",
    nameSP: " Apple iphone 7",
    price: 5000000,
    rate:5,
    title:"apple giá rẻ chính hãng",
    image:"image/SP/iphone7.jpg"
    },
    {id:'4',
    category:"phone",
    nameSP: " Apple iphone x",
    price: 7000000,
    rate:5,
    title:"apple giá rẻ chính hãng",
    image:"image/SP/iphonex.jpg"
    },
    {id:'5',
    category:"houseware",
    nameSP: " Bàn là hơi nước",
    price: 1000000,
    rate:5,
    title:"bàn là chính hảng panasonic",
    image:"image/SP/banla.jpg"
    },
    {id:'6',
    category:"houseware",
    nameSP: " ti vi OLED",
    price: 3500000,
    rate:5,
    title:"ti vi oled chính hảng sam sung",
    image:"image/SP/tivi.png"
    },
    {id:'7',
    category:"houseware",
    nameSP: " máy quạt cao cấp",
    price: 450000,
    rate:5,
    title:"máy quạt đứng cao cấp",
    image:"image/SP/mayquat.jpg"
    },
    {id:'8',
    category:"houseware",
    nameSP: " bình nóng lạnh",
    price: 1500000,
    rate:5,
    title:"bình nước nóng lạnh ",
    image:"image/SP/binhNuocNong.jpg"
    },
    {id:'9',
    category:"houseware",
    nameSP: " nồi cơm điện",
    price: 600000,
    rate:5,
    title:"nồi cơm điện nhật bản",
    image:"image/SP/noicom.jpg"
    },
]
 var local =localStorage.setItem('data',JSON.stringify(data))
 